# Generated by Django 4.2.10 on 2024-06-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("userName", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=40)),
                ("password", models.CharField(max_length=40)),
            ],
            options={"db_table": "UserInfo",},
        ),
    ]
