# Generated by Django 4.2.10 on 2024-06-27 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("userAuth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="verifyCodeDB",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.CharField(max_length=40)),
                ("code", models.CharField(max_length=10)),
                ("dateTime", models.DateTimeField(default=django.utils.timezone.now)),
                ("expire", models.IntegerField()),
            ],
        ),
    ]
